// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnijromffaalvpadojbj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaWpyb21mZmFhbHZwYWRvamJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMDAzNjYsImV4cCI6MjA3MDc3NjM2Nn0.i3vlN-B6_u0cwJzAYM-CpTKn7nvlaQOSa_u7DIg05Uc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});